global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'flask_app'
    metrics_path: /metrics
    static_configs:
      # If running Flask locally, Docker can reach it via host.docker.internal
      - targets: ['host.docker.internal:5000']


